### PR TITLE
Updated ToggleActiveBinding

### PR DESCRIPTION
**Pull request by MorganMoon**
- Changed how ToggleActiveBinding works (Sets the current GameObject as active / unactive rather than only its children)
- Added Adapter and adapteroptions to ToggleActiveBinding

### CODE REVIEW

**Comment by RoryDungan** [comment]
There are two different changes here so I'll address them separately. 

### Changing how ToggleActiveBinding works so that it works on the current GameObject rather than children
The reason this was originally designed to only turn children off and on is so that the UI can start with the child turned off, but still have the ToggleActiveBinding initialize itself to listen for updates. If we turn the object with the ToggleActiveBinding off in the editor, its `Awake()` method won't be called, which is necessary because it in turn calls `Init()`, which calls `Connect()`, which initialises the binding. 

With your solution all ToggleActiveBinding objects must be turned on at the start of the game, but when there are many panels that are off by default this can create clutter in the editor which makes the UI more difficult to work with. It also creates the problem that you need to play the game to see what the layout of the UI will actually look like when the game starts. 

If there is another advantage of doing it this way that we haven't thought of then we may be open to accepting this change, but otherwise I think we'll keep it the way it is.

### Adapter support

This is a very good addition and is something that we should have included originally. I'd like to accept it except that I think the implementation you have may throw an InvalidCastException when using an adapter. 

In the SyncFromSource code, if `viewModelEndPoint.GetValue()` returns a value that is not a bool, the cast to a bool on the first line will throw an InvalidCastException before it gets to the line that calls `adapter.Convert`
```
        private void SyncFromSource(PropertyEndPoint viewModelEndPoint)
        {
            bool input = (bool)viewModelEndPoint.GetValue();
            if (adapter != null)
            {
                input = (bool)adapter.Convert(input, viewAdapterOptions);
            }
        // ...
```

The best way to avoid this is to use a PropertySync with a PropertyEndPoint, because they handle converting with adapters internally. Have a look at the code in OneWayPropertyBinding for an example of how to use them. You should be able to copy the code from that class without many modifications to work for ToggleActiveBinding.

**Comment by MorganMoon** [comment]
Cool! I'll work on getting that right. I do have a question though, instead of working around the MonoBehaviour weirdness with Awake/No constructor, would you be against creating a "WeldContext" or something that we would have to have in the scene that could use https://docs.unity3d.com/ScriptReference/SceneManagement.Scene.GetRootGameObjects.html and 
https://docs.unity3d.com/ScriptReference/Component.GetComponentsInChildren.html to get all IMemberBinding components and call Init() on them? That way it sortof fixes the problems so there doesn't have to be (in my opinion) odd workarounds for something like the ToggleActiveBinding. It could also be changed in the Script Execution Order in unity to run before any awake methods are called.

Thanks!

**Comment by RoryDungan** [comment]
Having a "WeldContext" or something similar isn't a bad idea and we did consider it, but in the end decided that in terms of making the UI as easy to set up as possible, it would probably create more issues than it would solve. 

Neither adding a new object to every scene that uses Unity Weld or changing your project's Script Execution Order are obvious to new users of the library, and the kind of errors that incorrectly setting that up would cause would be hard for a new user to track down. Since we're targetting Weld for a use-case where (eventually) a programmer can write code and then the UI can be fully set up and bound by an artist or designer, we decided to prioritise making the initial setup as easy as possible.

Hope that answers your question and thanks again for your work!

**Comment by MorganMoon** [comment]
Alright, that decision makes sense and answers my question :)

**Comment by agent-reed** [comment]
I'd like to point out that this behavior (turning off only children) can have an undesirable effect when working with Layout Groups. Even when using an empty parent object, Layout Groups setup spacing and positioning of UI elements regardless of whether all the children are active or not. 

To remedy this, we've discovered that adding a one-way property binding to the "Ignore Layout" property with a BoolInversionAdapter bound to same boolean that controls the Toggle Active Binding will keep your layout group from acting as though the element is still a part of the collection. 

For example:
ignorelayout


Just wanted to share this finding in case it saved somebody some trouble down the road, and since it's directly related to this PR & Weld behavior.

**Pull request merged**
